# Generated by Django 4.2.1 on 2023-06-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_superuser_remove_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
