# Generated by Django 4.2.1 on 2023-06-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
